<?php

/**
 * Implements hook_menu().
 */
function tbulletin_menu() {

  $items['forum'] = array(
    'title' => 'Forums',
    'route_name' => 'tbulletin_forum_page',
    #'page callback' => 'tbulletin_forum_page',
    #'access arguments' => array('access content'),
    #'file' => 'forum.pages.inc',
  );
  $items['forum/%'] = array(
    'title' => 'Forums',
    'route_name' => 'tbulletin_topic_page'
    #'page callback' => 'tbulletin_topic_admin_page',
    #'page arguments' => array(1),
    #'access arguments' => array('access content'),
    #'type' => MENU_CALLBACK,
    #'file' => 'forum.pages.inc',
  );

  $items['admin/config/tbulletin'] = array(
    'title' => t('TBulletin'),
    'description' => 'Configure tbulletin.',
    'position' => 'left',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/tbulletin/forum'] = array(
    'title' => 'Forum settings',
    'route_name' => 'tbulletin_forum_settings',
  );

  $items['admin/config/tbulletin/forum/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/config/tbulletin/forum/posticon'] = array(
    'title' => 'Post Icons',
    'route_name' => 'tbulletin_forum_posticon',
  );
  return $items;
}


/**
 * Implements hook_permission().
 */
function tbulletin_permission() {
  $perms = array(
    'administer forums' => array(
      'title' => t('Administer forums'),
    ),
  );
  return $perms;
}



